<RenAgo>を追加しました
ycu-engine/ycu-engine.github.io pull request #38
Opened 2021-02-08 16:14 UTC by Rereren86

# 変更内容チェック

- [ ] データの変更
    - [x]  ユーザーの追加・修正
    - [ ] スキルの追加・修正
    - [ ] 学部等の追加・修正
    - [ ] チームの追加・修正
    - [ ] ポートフォリオの追加・修正
    - [ ] 活動記録の追加・修正
- [ ] ページの変更
    - [ ] 新しいページを追加
    - [ ] 既存のページを修正

2021-02-08 22:03 UTC, YutaUra requested changes
いくつか変更して欲しい箇所があります！
お願いします！わからないことがあれば遠慮なくSlack送ってください！

2021-02-08 22:03 UTC, YutaUra commented on src/data/member.ts
> +    joinedAt: zonedTimeToUtc('2021-02-09','Asia/Tokyo'),
`joinedAt: zonedTimeToUtc('2021-02-09','Asia/Tokyo'),`を

`joinedAt: zonedTimeToUtc('2021-02-09', 'Asia/Tokyo'),`に変えてください！（スペースを1つ追加）

2021-02-08 22:03 UTC, YutaUra commented on src/data/member.ts
> +    belongs: {facultyName: 'DataScienceUndergraduate',grade: 1},
`belongs: {facultyName: 'DataScienceUndergraduate',grade: 1},`を

`belongs: { facultyName: 'DataScienceUndergraduate', grade: 1 },`に変えてください！（スペースを３つ追加）

2021-02-09 12:47 UTC, Rereren86 commented on src/data/member.ts
> +    belongs: {facultyName: 'DataScienceUndergraduate',grade: 1},
了解しました。

2021-02-10 02:02 UTC, YutaUra approved these changes
LGTM！

2021-02-10 02:02 UTC, merged